// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Skeleton.Mac
{
	public partial class FileTableView : NSTableView
	{
		public FileTableView (IntPtr handle) : base (handle)
		{
            
		}

		public override void AwakeFromNib()
		{
            base.AwakeFromNib();
            var filemenu = new NSMenu();
            filemenu.AddItem(new NSMenuItem() { Title = "ddd" });
            filemenu.AddItem(new NSMenuItem() { Title = "aaa" });
            filemenu.AddItem(new NSMenuItem() { Title = "bbb" });
            this.Menu = filemenu;
		}

		public override void SelectCell(NSCell aCell)
		{
            base.SelectCell(aCell);
		}

		public override void SelectRows(NSIndexSet indexes, bool byExtendingSelection)
		{
            base.SelectRows(indexes, byExtendingSelection);
		}

		public override void WillOpenMenu(NSMenu menu, NSEvent theEvent)
		{
            base.WillOpenMenu(menu, theEvent);
		}
	}
}
