// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Skeleton.Mac
{
	public partial class ContactTableView : NSTableView
	{
		public ContactTableView (IntPtr handle) : base (handle)
		{
		}
	}
}
