// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
namespace Skeleton.Mac
{
	public partial class ContactViewController : NSViewController
	{
		public ContactViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
            base.ViewDidLoad();
		}
	}
}
