// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using Skeleton.Mac.FilesTableView;

namespace Skeleton.Mac
{
	public partial class FileViewController : NSViewController
	{
		public FileViewController (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib()
		{
            base.AwakeFromNib();
            var DataSource = new FileItemTableDataSource();
            DataSource.Files.Add(new FileItem());
            DataSource.Files.Add(new FileItem());
            DataSource.Files.Add(new FileItem());

            FileTable.DataSource = DataSource;
            FileTable.Delegate = new FileTableDelegate(DataSource);
		}
	}
}
